# Generated by Django 3.2.5 on 2022-04-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='pics')),
                ('page1', models.CharField(max_length=20)),
                ('page2', models.CharField(max_length=20)),
                ('page3', models.CharField(max_length=20)),
                ('page4', models.CharField(max_length=20)),
                ('cart', models.BooleanField(default=True)),
                ('search', models.BooleanField(default=True)),
                ('sign_up', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_head', models.TextField()),
                ('black_head', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('adress', models.TextField()),
                ('email', models.EmailField(max_length=128)),
                ('phone_number', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('price', models.FloatField()),
                ('is_ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('discount', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='pics')),
                ('notice_image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
