# Generated by Django 3.2.5 on 2022-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('discount', models.BooleanField(default=False)),
            ],
        ),
    ]
