# Generated by Django 3.2.5 on 2022-04-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='pics')),
                ('page1', models.CharField(max_length=10)),
                ('page2', models.CharField(max_length=10)),
                ('page3', models.CharField(max_length=10)),
                ('page4', models.CharField(max_length=10)),
                ('cart', models.BooleanField(default=True)),
                ('search', models.BooleanField(default=True)),
                ('sign_up', models.BooleanField(default=True)),
            ],
        ),
    ]
