# Generated by Django 3.2.5 on 2022-04-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_head', models.TextField()),
                ('black_head', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='page1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='page2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='page3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='page4',
            field=models.CharField(max_length=20),
        ),
    ]
